/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Notepad;

import java.awt.Font;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.Element;
import javax.swing.undo.UndoManager;

/**
 **************************************
 * @author Ghulam Sakhi Sahil * *************************************
 */
public class notepad extends javax.swing.JFrame {

// Declare FileChooser
    private File openedFile;
    private boolean changeMade = false;
    private final UndoManager undoManager = new UndoManager();

    /**
     * Creates new form NewJFrame
     */
    public notepad() {
        initComponents();
        textPane.getDocument().addUndoableEditListener(undoManager);
        ImageIcon icon = new ImageIcon(getClass().getResource("Notepad.png"));
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        Cut = new javax.swing.JMenuItem();
        Copy = new javax.swing.JMenuItem();
        Paste = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        createNewFile = new javax.swing.JMenuItem();
        openFile = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        SaveMenu = new javax.swing.JMenuItem();
        SaveAsMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        printFile = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        cut = new javax.swing.JMenuItem();
        copy = new javax.swing.JMenuItem();
        paste = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        undo = new javax.swing.JMenuItem();
        redo = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        goToLine = new javax.swing.JMenuItem();
        selectAll = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        insertDate = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        setFont = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        popupMenu.setLabel("");
        popupMenu.setName(""); // NOI18N
        popupMenu.setRequestFocusEnabled(false);

        Cut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Cut.setText("Cut");
        Cut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cut.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Cut.setIconTextGap(0);
        Cut.setName(""); // NOI18N
        Cut.setPreferredSize(new java.awt.Dimension(119, 30));
        Cut.setRequestFocusEnabled(false);
        Cut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CutActionPerformed(evt);
            }
        });
        popupMenu.add(Cut);

        Copy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Copy.setText("Copy");
        Copy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Copy.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Copy.setIconTextGap(0);
        Copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyActionPerformed(evt);
            }
        });
        popupMenu.add(Copy);

        Paste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Paste.setText("Paste");
        Paste.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Paste.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Paste.setIconTextGap(0);
        Paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasteActionPerformed(evt);
            }
        });
        popupMenu.add(Paste);

        Delete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        Delete.setText("Delete");
        Delete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Delete.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Delete.setIconTextGap(0);
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        popupMenu.add(Delete);

        popupMenu.getAccessibleContext().setAccessibleParent(textPane);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Untitled - Java Notepad");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(null);

        textPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 5, 5));
        textPane.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        textPane.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textPane.setFocusTraversalPolicyProvider(true);
        textPane.setMargin(new java.awt.Insets(0, 0, 0, 0));
        textPane.setPreferredSize(new java.awt.Dimension(780, 400));
        textPane.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        textPane.setSelectionColor(new java.awt.Color(143, 201, 255));
        textPane.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textPaneCaretUpdate(evt);
            }
        });
        textPane.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textPaneFocusGained(evt);
            }
        });
        textPane.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                textPaneInputMethodTextChanged(evt);
            }
        });
        // Attach the popup menu to the text area
        textPane.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                showPopup(e);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                showPopup(e);
            }

            private void showPopup(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    popupMenu.show(textPane, e.getX(), e.getY());
                }
            }
        });
        jScrollPane2.setViewportView(textPane);
        textPane.getDocument().addDocumentListener(documentListener);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setToolTipText("");
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(799, 25));

        jLabel1.setText("Ln 1, Col 1");

        jLabel2.setText("0 words");

        jLabel3.setText("0 characters");

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator10)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jMenuBar2.setBackground(javax.swing.UIManager.getDefaults().getColor("inactiveCaption"));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 1));
        jMenuBar2.setBorderPainted(false);
        jMenuBar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar2.setMargin(new java.awt.Insets(5, 15, 5, 0));
        jMenuBar2.setPreferredSize(new java.awt.Dimension(75, 30));

        jMenu4.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jMenu4.setText("File");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        createNewFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        createNewFile.setText("New");
        createNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewFileActionPerformed(evt);
            }
        });
        jMenu4.add(createNewFile);

        openFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openFile.setText("Open");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        jMenu4.add(openFile);
        jMenu4.add(jSeparator3);

        SaveMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SaveMenu.setText("Save");
        SaveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveMenuActionPerformed(evt);
            }
        });
        jMenu4.add(SaveMenu);

        SaveAsMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SaveAsMenu.setText("Save As");
        SaveAsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsMenuActionPerformed(evt);
            }
        });
        jMenu4.add(SaveAsMenu);
        jMenu4.add(jSeparator2);

        printFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        printFile.setText("Print");
        printFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printFileActionPerformed(evt);
            }
        });
        jMenu4.add(printFile);
        jMenu4.add(jSeparator1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setText("Close");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar2.add(jMenu4);

        jMenu5.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jMenu5.setText("Edit");
        jMenu5.setIconTextGap(0);

        cut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cut.setText("Cut");
        cut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutActionPerformed(evt);
            }
        });
        jMenu5.add(cut);

        copy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        copy.setText("Copy");
        copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyActionPerformed(evt);
            }
        });
        jMenu5.add(copy);

        paste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        paste.setText("Paste");
        paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteActionPerformed(evt);
            }
        });
        jMenu5.add(paste);
        jMenu5.add(jSeparator4);

        undo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        undo.setText("Undo");
        undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoActionPerformed(evt);
            }
        });
        jMenu5.add(undo);

        redo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        redo.setText("Redo");
        redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoActionPerformed(evt);
            }
        });
        jMenu5.add(redo);
        jMenu5.add(jSeparator5);

        goToLine.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        goToLine.setText("Go to");
        goToLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToLineActionPerformed(evt);
            }
        });
        jMenu5.add(goToLine);

        selectAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        selectAll.setText("Select All");
        selectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllActionPerformed(evt);
            }
        });
        jMenu5.add(selectAll);
        jMenu5.add(jSeparator6);

        insertDate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        insertDate.setText("Time/Date");
        insertDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertDateActionPerformed(evt);
            }
        });
        jMenu5.add(insertDate);
        jMenu5.add(jSeparator7);

        setFont.setText("Font");
        setFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setFontActionPerformed(evt);
            }
        });
        jMenu5.add(setFont);

        jMenuBar2.add(jMenu5);

        jMenu7.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jMenu7.setText("Help");

        about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenu7.add(about);

        jMenuBar2.add(jMenu7);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Document Listener to track changes in the text area
    private final DocumentListener documentListener = new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            changeMade = true;
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            changeMade = true;
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            // Plain text components don't fire these events
        }
    };

    // Update line, column, and character/word counts
    private void updateLabels() {
        updateLineAndColumn();
        updateCharacterCount();
        updateWordCount();
    }

    private void updateLineAndColumn() {
        int caretPosition = textPane.getCaretPosition();
        int lineNumber = 1;
        int columnNumber = 1;

        try {
            Element root = textPane.getDocument().getDefaultRootElement();
            lineNumber = root.getElementIndex(caretPosition) + 1;
            int lineStartOffset = root.getElement(lineNumber - 1).getStartOffset();
            columnNumber = caretPosition - lineStartOffset + 1;
        } catch (Exception e) {
            // Handle exception if necessary
        }

        jLabel1.setText("Ln " + lineNumber + ", Col " + columnNumber);
    }

    private void updateCharacterCount() {
        String text = textPane.getText().replaceAll("\\s+", "");
        int charCount = text.length();
        jLabel3.setText(charCount + " characters");
    }

    private void updateWordCount() {
        String text = textPane.getText().trim();
        int wordCount = text.isEmpty() ? 0 : text.split("\\s+").length;
        jLabel2.setText(wordCount + " Word Count");
    }

    // Save file method
    private void saveFile(File file) {
        try ( FileWriter writer = new FileWriter(file)) {
            writer.write(textPane.getText());
            openedFile = file;
            changeMade = false;
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void save() {
        if (openedFile != null) {
            saveFile(openedFile);
        } else {
            saveAs();
        }
        updateTitle();
    }

    private void saveAs() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Text Files (*.txt)", "txt"));
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int returnVal = fileChooser.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            file = ensureFileExtension(file, "txt");

            if (file.exists() && !confirmOverwrite()) {
                return;
            }

            saveFile(file);
            updateTitle();
        }
    }

    private File ensureFileExtension(File file, String extension) {
        String fileName = file.getName();
        if (!fileName.toLowerCase().endsWith("." + extension)) {
            file = new File(file.getAbsolutePath() + "." + extension);
        }
        return file;
    }

    private boolean confirmOverwrite() {
        int result = JOptionPane.showConfirmDialog(this, "The file already exists. Do you want to overwrite it?", "Confirm Overwrite", JOptionPane.YES_NO_OPTION);
        return result == JOptionPane.YES_OPTION;
    }

    private void updateTitle() {
        if (openedFile != null) {
            setTitle(openedFile.getName() + " - Java Notepad");
        } else {
            setTitle("untitled - Java Notepad");
        }
    }


    private void SaveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveMenuActionPerformed
        save();
    }//GEN-LAST:event_SaveMenuActionPerformed

    private void SaveAsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsMenuActionPerformed
        saveAs();
    }//GEN-LAST:event_SaveAsMenuActionPerformed

    private String getFileExtension(String fileName) {
        int dotIndex = fileName.lastIndexOf('.');
        return (dotIndex == -1) ? "" : fileName.substring(dotIndex + 1).toLowerCase();
    }


    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Text Files", "txt"));

        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            try {
                String content = Files.readString(file.toPath());
                textPane.setText(content);
                openedFile = file;
                updateTitle();
                changeMade = false;
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error reading file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_openFileActionPerformed

    private void createNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewFileActionPerformed

        // Check if there are unsaved changes
        if (changeMade) {
            int result = JOptionPane.showConfirmDialog(this, "Do you want to save changes before creating a new file?", "Save Changes", JOptionPane.YES_NO_CANCEL_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                save();
            } else if (result == JOptionPane.CANCEL_OPTION) {
                return;
            }
        }
        textPane.setText("");
        openedFile = null;
        updateTitle();

    }//GEN-LAST:event_createNewFileActionPerformed

    private void printFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printFileActionPerformed
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        if (printerJob.printDialog()) {
            try {
                printerJob.print();
            } catch (PrinterException ex) {
                JOptionPane.showMessageDialog(null, "Error printing: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_printFileActionPerformed

    private void setFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setFontActionPerformed
        JFontChooser fontChooser = new JFontChooser();
        int result = fontChooser.showDialog(this);
        if (result == JFontChooser.OK_OPTION) {
            Font selectedFont = fontChooser.getSelectedFont();
            if (selectedFont != null) {
                textPane.setFont(selectedFont);
            }
        }
    }//GEN-LAST:event_setFontActionPerformed

    private void insertDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDateActionPerformed
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss a");
        textPane.setText(textPane.getText() + df.format(new Date()));
    }//GEN-LAST:event_insertDateActionPerformed

    private void cutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutActionPerformed
        textPane.cut();

    }//GEN-LAST:event_cutActionPerformed

    private void copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyActionPerformed
        textPane.copy();
    }//GEN-LAST:event_copyActionPerformed

    private void pasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteActionPerformed
        textPane.paste();
    }//GEN-LAST:event_pasteActionPerformed

    private void undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoActionPerformed
        if (undoManager.canUndo()) {
            undoManager.undo();
        }
    }//GEN-LAST:event_undoActionPerformed

    private void redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoActionPerformed
        if (undoManager.canRedo()) {
            undoManager.redo();
        }
    }//GEN-LAST:event_redoActionPerformed

    private void selectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllActionPerformed
        textPane.selectAll();
    }//GEN-LAST:event_selectAllActionPerformed

    private void goToLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToLineActionPerformed

        String line = JOptionPane.showInputDialog(this, "Enter the Line Number");

        try {
            if (!line.isEmpty() && line != null) {

                int numline = Integer.parseInt(line);
                int startOfset = textPane.getDocument().getDefaultRootElement().getElement(numline - 1).getStartOffset();
                textPane.setCaretPosition(startOfset);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Line not found", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_goToLineActionPerformed

    private void textPaneCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_textPaneCaretUpdate
        updateLabels();
    }//GEN-LAST:event_textPaneCaretUpdate

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        AboutForm about = new AboutForm(this, true);
        about.setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (changeMade) {
            int option = JOptionPane.showConfirmDialog(this, "Do you want to save the file?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                save();
            }
            if (option == JOptionPane.CANCEL_OPTION) {
                return;
            }
        }
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void textPaneInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_textPaneInputMethodTextChanged

    }//GEN-LAST:event_textPaneInputMethodTextChanged

    private void textPaneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPaneFocusGained
        updateLabels();
    }//GEN-LAST:event_textPaneFocusGained

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        textPane.replaceSelection("");
    }//GEN-LAST:event_DeleteActionPerformed

    private void CopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyActionPerformed
        textPane.copy();
    }//GEN-LAST:event_CopyActionPerformed

    private void PasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasteActionPerformed
        textPane.paste();
    }//GEN-LAST:event_PasteActionPerformed
    private void CutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CutActionPerformed
        textPane.cut();
    }//GEN-LAST:event_CutActionPerformed
    
      /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(notepad.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        // Check if there are command-line arguments
        if (args.length > 0) {
            // Attempt to open the file specified by the first command-line argument
            File file = new File(args[0]);
            if (file.exists() && file.isFile()) {
                try {
                    String content = Files.readString(file.toPath());
                    notepad app = new notepad();
                    app.setVisible(true);
                    app.textPane.setText(content);
                    app.openedFile = file;
                    app.updateTitle();
                    app.changeMade = false;
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Error reading file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Invalid file specified: " + args[0], "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // No command-line arguments, proceed with normal application flow
            java.awt.EventQueue.invokeLater(() -> {
                new notepad().setVisible(true);
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Copy;
    private javax.swing.JMenuItem Cut;
    private javax.swing.JMenuItem Delete;
    private javax.swing.JMenuItem Paste;
    private javax.swing.JMenuItem SaveAsMenu;
    private javax.swing.JMenuItem SaveMenu;
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem copy;
    private javax.swing.JMenuItem createNewFile;
    private javax.swing.JMenuItem cut;
    private javax.swing.JMenuItem goToLine;
    private javax.swing.JMenuItem insertDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JMenuItem openFile;
    private javax.swing.JMenuItem paste;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JMenuItem printFile;
    private javax.swing.JMenuItem redo;
    private javax.swing.JMenuItem selectAll;
    private javax.swing.JMenuItem setFont;
    private javax.swing.JTextPane textPane;
    private javax.swing.JMenuItem undo;
    // End of variables declaration//GEN-END:variables

}
